from abc import ABC,abstractmethod
from torch import Tensor
class MappingStateInterface(ABC):
    def generate_model_args(self) -> list[Tensor]:
        ...
    def get_legal_actions(self) -> list:
        ...
    def get_action_to_index_policy_logits(self):
        ...
    def mapping_is_valid(self):
        ...
    def set_mapping_is_valid(self):
        ...
        
